### ISSUE TITLE
Incompatible with BCLib

### ISSUE THREAD

**Issue by KingBophades** [Techno573/techno-backrooms-mod#1]
When loading this mod with [BCLib](https://www.curseforge.com/minecraft/mc-mods/bclib), it makes all 8 levels generate incorrectly.

![Level 0](https://user-images.githubusercontent.com/30759644/182740569-4753b1b0-1040-4e4e-9464-9dea9c36fec6.png)
![Level 1](https://user-images.githubusercontent.com/30759644/182742161-f445f06e-9329-46c9-a5e3-f52c88ff2b3d.png)
![Level 2](https://user-images.githubusercontent.com/30759644/182742207-23d11b18-6740-48b2-be79-d35be5d5cb3b.png)
![Level 3](https://user-images.githubusercontent.com/30759644/182742480-3277cb62-515d-4709-8e6f-8f427218de99.png)
![Level FUN](https://user-images.githubusercontent.com/30759644/182742542-4174f5b2-2856-42a5-a5c1-634c6cd46fa3.png)

### Additional context
_Can be easily reproduced_
**Minecraft Ver:** 1.18.2
**Fabric Loader Ver:** 0.14.8

**Comment by Techno573** [comment]
> When loading this mod with [BCLib](https://www.curseforge.com/minecraft/mc-mods/bclib), it makes all 8 levels generate incorrectly.
> 
> ![Level 0](https://user-images.githubusercontent.com/30759644/182740569-4753b1b0-1040-4e4e-9464-9dea9c36fec6.png) ![Level 1](https://user-images.githubusercontent.com/30759644/182742161-f445f06e-9329-46c9-a5e3-f52c88ff2b3d.png) ![Level 2](https://user-images.githubusercontent.com/30759644/182742207-23d11b18-6740-48b2-be79-d35be5d5cb3b.png) ![Level 3](https://user-images.githubusercontent.com/30759644/182742480-3277cb62-515d-4709-8e6f-8f427218de99.png) ![Level FUN](https://user-images.githubusercontent.com/30759644/182742542-4174f5b2-2856-42a5-a5c1-634c6cd46fa3.png)
> 
> ### Additional context
> _Can be easily reproduced_ **Minecraft Ver:** 1.18.2 **Fabric Loader Ver:** 0.14.8

I’m already aware of this bug. Sadly, I don’t know how to fix it yet. My recommended solution (at least until I find out how to fix this) is to not use BCLib and my mod at the same time.
